/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as carameloPreSaleSol from "./CarameloPreSale.sol";
export * as interfaces from "./interfaces";
export { Caramelo__factory } from "./Caramelo__factory";
