/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { ReentrancyGuard } from "./@openzeppelin/contracts/utils/ReentrancyGuard";
export { ReentrancyGuard__factory } from "./factories/@openzeppelin/contracts/utils/ReentrancyGuard__factory";
export type { Caramelo } from "./contracts/Caramelo";
export { Caramelo__factory } from "./factories/contracts/Caramelo__factory";
export type { CarameloPreSale } from "./contracts/CarameloPreSale.sol/CarameloPreSale";
export { CarameloPreSale__factory } from "./factories/contracts/CarameloPreSale.sol/CarameloPreSale__factory";
export type { IERC20 } from "./contracts/CarameloPreSale.sol/IERC20";
export { IERC20__factory } from "./factories/contracts/CarameloPreSale.sol/IERC20__factory";
export type { IUniswapV2Factory } from "./contracts/interfaces/UniswapV2Interfaces.sol/IUniswapV2Factory";
export { IUniswapV2Factory__factory } from "./factories/contracts/interfaces/UniswapV2Interfaces.sol/IUniswapV2Factory__factory";
export type { IUniswapV2Pair } from "./contracts/interfaces/UniswapV2Interfaces.sol/IUniswapV2Pair";
export { IUniswapV2Pair__factory } from "./factories/contracts/interfaces/UniswapV2Interfaces.sol/IUniswapV2Pair__factory";
export type { IUniswapV2Router02 } from "./contracts/interfaces/UniswapV2Interfaces.sol/IUniswapV2Router02";
export { IUniswapV2Router02__factory } from "./factories/contracts/interfaces/UniswapV2Interfaces.sol/IUniswapV2Router02__factory";
