/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carameloPreSaleSol from "./CarameloPreSale.sol";
export type { carameloPreSaleSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Caramelo } from "./Caramelo";
